import localFont from "next/font/local";
import { Roboto  } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { CartProvider } from "./_context/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
 const roboto = Roboto({
  subsets: ["latin"],
  weight: [ "700"], // أو أي أوزان تحتاجها
  // variable: "--font-roboto",
  // display: "swap",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
              <body
        // className={`
        //    ${geistSans.variable} 
        //    ${geistMono.variable}
        //    ${inter.variable} 
        //    antialiased`}

        // className="{roboto.variable}"
        className={roboto.className}
        
      >
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
