import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { CartProvider } from "./_context/CartContext";

// Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["700"],
});

// Viewport for proper mobile scaling
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body
        className={[
          roboto.className,
          geistSans.variable,
          geistMono.variable,
          // Layout fixes
          "min-h-screen flex flex-col overflow-x-hidden antialiased bg-white text-gray-900",
        ].join(" ")}
      >
        <CartProvider>
          <Header />

          {/* صفحة متجاوبة: Container موحد لكل الصفحات */}
          <main className="flex-1">
            <div className="container mx-auto w-full max-w-screen-xl px-3 sm:px-4 md:px-6 lg:px-8 py-6 sm:py-8">
              {children}
            </div>
          </main>

          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
